# --------------------------------------------------------------------------------------------------------------------------------------------------------
### Main Section

# Main Modes
generate_test_label_mode: False                                 # Set to True to generate test labels for input_file only
training_mode: False                                             # Set to True to enable training mode
evaluation_mode: True                                          # Set to True to enable evaluation mode
inference_mode: True                                            # Set to True to enable inference mode



# Model Prediction Modes
repeat_purchase_mode: True                                       # Set to True to enable repeat purchase modeling
property_type_mode: True                                         # Set to True to enable property type modeling






# --------------------------------------------------------------------------------------------------------------------------------------------------------
### Data Preparation Section
# This section is responsible for preparing data before model training and evaluation or inference.

save_output: True                                                 # Set to True to save the output of the data preparation
load_df_from_checkpoint: True                                     # Set to True to load the DataFrame from a checkpoint
split_df_for_eval: True                                           # Set to True to split the input_file for evaluation based on the evaluation_start_date and evaluation_end_date

# File paths for data preparation (USER NEED TO MAINTAIN)
input_file: /content/drive/MyDrive/raw_data/raw_data.csv                                      # Path to the input raw data file
data_extraction_columns_file: /content/customer_profiling/columns/columns_to_extract.csv       # Path to the csv file that stores columns to be extract for data preparation
feature_mapping_dir: /content/customer_profiling/feature_mapping/                             # Directory for feature mappings


# Directories for derived data and reports                        
derived_data_dir: /content/customer_profiling/derived_data/        # Directory to save derived data
data_report_dir: /content/customer_profiling/data_report/          # Directory to save data reports
save_dir: /content/output/                                        # Directory to save the final output







# --------------------------------------------------------------------------------------------------------------------------------------------------------
### Test Label Generation Section
# This section handles the generation of test labels based on specified criteria.

# Input for test file only when "split_df_for_eval" is False; 
# Program will use "for_eval_label_generation.csv" if "split_df_for_eval" is True

test_file: /content/drive/MyDrive/temp_data/after_2022_df.csv     # Path to the test file
evaluation_start_date: 2023-01-03 #yyyy-mm-dd                    # Start date for evaluation
evaluation_end_date: 2023-12-30 #yyyy-mm-dd                      # End date for evaluation







# --------------------------------------------------------------------------------------------------------------------------------------------------------
### Repeat Purchase Mode Section
# This section configures the repeat purchase prediction model.

rp_model : catboost                                                                            # Model type for repeat purchase prediction
#Possible values: logistic_regression, knn, svm, decision_tree, random_forest, gradient_boosting, lightgbm, catboost, mlp

rp_model_dir: /content/customer_profiling/models/rp_model/                                       # Directory for the repeat purchase model

# Repeat purchase model training
rp_model_columns_file: /content/customer_profiling/columns/rp_model_columns_to_extract.csv       # Path to the columns for the repeat purchase model
bagging_split: 3                                                                                # Number of bagging splits for training
down_sampling: True                                                                             # Set to True to enable down sampling
down_sampling_ratio: 1                                                                          # Ratio for down sampling
rp_validation_split: 0.2                                                                        # Validation split ratio

# Repeat purchase model testing
inference_threshold: 0.6                                                                        # Threshold for inference
rp_result_dir: /content/1_rp_result/                                                            # Directory to save repeat purchase model results









# --------------------------------------------------------------------------------------------------------------------------------------------------------------
### Property Type Mode Section
# This section configures the property type prediction model.

pt_model : catboost                                                                         # Model type for property type prediction
#Possible values: logistic_regression, knn, svm, decision_tree, random_forest, gradient_boosting, lightgbm, catboost, mlp
pt_model_dir: /content/customer_profiling/models/pt_model/                                    # Directory for the property type model


# Property type model training
pt_model_columns_file: /content/customer_profiling/columns/pt_model_columns_to_extract.csv     # Path to the columns for the property type model
pt_validation_split: 0.2

# Property type model testing
landed_mode: True                                                                             # Set to True to enable landed property type mode
high_rise_mode: True                                                                          # Set to True to enable high-rise property type mode
commercial_mode: True                                                                         # Set to True to enable commercial property type mode
pt_result_dir: /content/2_pt_result/
